hitsTitles = ['BROTHERS IN ARMS','BOHEMIAN RHAPSODY','STAIRWAY TO HEAVEN','RIDERS ON THE STORM','WISH YOU WERE HERE']
print(hitsTitles)
print('\n')
print('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')
print('\n')
newList = ['CHILD IN TIME','AGAIN']
hitsTitles.extend(newList)
#hitsTitles.append('CHILD IN TIME') - appendem tez mozna dodac do listy na koncu
#hitsTitles.append('AGAIN')
#print(hitsTitles)
print(hitsTitles)
print('\n')
print('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')
print('\n')
hitsTitles.insert(2,'HOTEL CALIFORNIA')
print(hitsTitles)
print('\n')
print('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')
print('\n')
hitsTitles.insert(0,'THE SOUND OF SILENCE')
print(hitsTitles)
print('\n')
print('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')
print('\n')
print(hitsTitles.index('HOTEL CALIFORNIA'))
print('\n')
print('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')
print('\n')
hitsTitles.remove('HOTEL CALIFORNIA')
print(hitsTitles)
print('\n')
print('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')
print('\n')
hitsTitles.remove('THE SOUND OF SILENCE')
hitsTitles.insert(0,'ENJOY THE SILENCE')
print(hitsTitles)
print('\n')
print('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')
print('\n')
hitsToRead = hitsTitles.copy()
hitsToRead.reverse()
print(hitsToRead)
print('\n')
print('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@')
print('\n')
hitsToRead.sort() #polecenie sortuje uwzgledniajac wielkosc liter
#hitsToRead.sort(key=str.lower) sortuje bez uwzgledniania wielkosci liter
print(hitsToRead)
print('\n')
print('$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$')
print('\n')
print(hitsToRead.pop(0))
print(hitsToRead.pop(0))
print(hitsToRead)
print('\n')
print('$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$')
print('\n')
additionalSongs = ['NOTHING COMPARES 2 U','WISH YOU WERE HERE']
hitsToRead.extend(additionalSongs)
print(hitsToRead)
print(hitsToRead.count('WISH YOU WERE HERE'))
print(hitsToRead.count('RIDERS ON THE STORM'))
hitsToRead.clear()
print(hitsToRead)
